import type { Config } from 'tailwindcss'

const config = {
  darkMode: ['class'],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        'neutralblackb-100': 'var(--neutralblackb-100)',
        'neutralblackb-200': 'var(--neutralblackb-200)',
        'neutralblackb-300': 'var(--neutralblackb-300)',
        'neutralblackb-400': 'var(--neutralblackb-400)',
        'neutralblackb-500': 'var(--neutralblackb-500)',
        'neutralblackb-600': 'var(--neutralblackb-600)',
        'neutralblackb-700': 'var(--neutralblackb-700)',
        'neutralblackb-800': 'var(--neutralblackb-800)',
        'neutralblackb-900': 'var(--neutralblackb-900)',
        'neutralwhitew-100': 'var(--neutralwhitew-100)',
        'neutralwhitew-200': 'var(--neutralwhitew-200)',
        'neutralwhitew-900': 'var(--neutralwhitew-900)',
        'primaryb-100': 'var(--primaryb-100)',
        'primaryb-200': 'var(--primaryb-200)',
        'primaryb-300': 'var(--primaryb-300)',
        'primaryb-400': 'var(--primaryb-400)',
        'primaryb-500': 'var(--primaryb-500)',
        'primaryb-600': 'var(--primaryb-600)',
        'primaryb-700': 'var(--primaryb-700)',
        'primaryb-800': 'var(--primaryb-800)',
        'primaryb-900': 'var(--primaryb-900)',
        'semanticblueb-100': 'var(--semanticblueb-100)',
        'semanticblueb-200': 'var(--semanticblueb-200)',
        'semanticblueb-300': 'var(--semanticblueb-300)',
        'semanticblueb-400': 'var(--semanticblueb-400)',
        'semanticblueb-500': 'var(--semanticblueb-500)',
        'semanticblueb-600': 'var(--semanticblueb-600)',
        'semanticblueb-700': 'var(--semanticblueb-700)',
        'semanticblueb-800': 'var(--semanticblueb-800)',
        'semanticblueb-900': 'var(--semanticblueb-900)',
        'semanticgreeng-100': 'var(--semanticgreeng-100)',
        'semanticgreeng-200': 'var(--semanticgreeng-200)',
        'semanticgreeng-300': 'var(--semanticgreeng-300)',
        'semanticgreeng-400': 'var(--semanticgreeng-400)',
        'semanticgreeng-500': 'var(--semanticgreeng-500)',
        'semanticgreeng-600': 'var(--semanticgreeng-600)',
        'semanticgreeng-700': 'var(--semanticgreeng-700)',
        'semanticgreeng-800': 'var(--semanticgreeng-800)',
        'semanticgreeng-900': 'var(--semanticgreeng-900)',
        'semanticredr-100': 'var(--semanticredr-100)',
        'semanticredr-200': 'var(--semanticredr-200)',
        'semanticredr-300': 'var(--semanticredr-300)',
        'semanticredr-400': 'var(--semanticredr-400)',
        'semanticredr-500': 'var(--semanticredr-500)',
        'semanticredr-600': 'var(--semanticredr-600)',
        'semanticredr-700': 'var(--semanticredr-700)',
        'semanticredr-800': 'var(--semanticredr-800)',
        'semanticredr-900': 'var(--semanticredr-900)',
        'semanticyellowy-100': 'var(--semanticyellowy-100)',
        'semanticyellowy-200': 'var(--semanticyellowy-200)',
        'semanticyellowy-300': 'var(--semanticyellowy-300)',
        'semanticyellowy-400': 'var(--semanticyellowy-400)',
        'semanticyellowy-500': 'var(--semanticyellowy-500)',
        'semanticyellowy-600': 'var(--semanticyellowy-600)',
        'semanticyellowy-700': 'var(--semanticyellowy-700)',
        'semanticyellowy-800': 'var(--semanticyellowy-800)',
        'semanticyellowy-900': 'var(--semanticyellowy-900)',
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      fontFamily: {
        'body-medium': 'var(--body-medium-font-family)',
        'body-regular': 'var(--body-regular-font-family)',
        'heading-h1-tight-semi-bold':
          'var(--heading-h1-tight-semi-bold-font-family)',
        'heading-h2-normal-bold': 'var(--heading-h2-normal-bold-font-family)',
        'heading-h2-tight-semi-bold':
          'var(--heading-h2-tight-semi-bold-font-family)',
        'heading-h3-nomal-bold': 'var(--heading-h3-nomal-bold-font-family)',
        'heading-h4-normal-medium':
          'var(--heading-h4-normal-medium-font-family)',
        'heading-h4-normal-semibold':
          'var(--heading-h4-normal-semibold-font-family)',
        'heading-h5-normal-semi-bold':
          'var(--heading-h5-normal-semi-bold-font-family)',
        'heading-h6-medium': 'var(--heading-h6-medium-font-family)',
        'label-loose-medium': 'var(--label-loose-medium-font-family)',
        'label-normal-medium': 'var(--label-normal-medium-font-family)',
      },
      boxShadow: {
        'shadow-medium': 'var(--shadow-medium)',
        'shadow-small': 'var(--shadow-small)',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config

export default config
